"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 21:44:17.044025

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("stats_snapshot", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problems",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("ac_rate", sa.Double(), nullable=True),
        sa.Column("topic_tags", sa.JSON(), nullable=False),
        sa.Column("similar_questions", sa.JSON(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("merged_into", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merged_into"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_state",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "cards",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("due", sa.DateTime(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.Column("last_review", sa.DateTime(), nullable=True),
        sa.Column("suspended", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cards_due"), ["due"], unique=False)

    op.create_table(
        "problem_analysis",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("techniques", sa.JSON(), nullable=False),
        sa.Column("key_insight", sa.Text(), nullable=True),
        sa.Column("what_makes_it_hard", sa.Text(), nullable=True),
        sa.Column("optimal_time", sa.String(), nullable=True),
        sa.Column("optimal_space", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "problem_skills",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("slug", "skill_id"),
    )
    with op.batch_alter_table("problem_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_problem_skills_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "skill_edges",
        sa.Column("from_skill", sa.Integer(), nullable=False),
        sa.Column("to_skill", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_skill"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_skill"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("from_skill", "to_skill", "type"),
    )
    op.create_table(
        "submissions",
        sa.Column("submission_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("runtime_ms", sa.Integer(), nullable=True),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("code_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_submissions_code_hash"), ["code_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_submissions_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_submissions_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "suggestions",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("date", "slug"),
    )
    op.create_table(
        "solution_analysis",
        sa.Column("submission_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("approach", sa.Text(), nullable=True),
        sa.Column("time_complexity", sa.String(), nullable=True),
        sa.Column("space_complexity", sa.String(), nullable=True),
        sa.Column("is_optimal", sa.Boolean(), nullable=True),
        sa.Column("mistakes", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.submission_id"],
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    op.create_table(
        "solves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("accepted_submission_id", sa.Integer(), nullable=False),
        sa.Column("wrong_before_ac", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("rating_inferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_submission_id"],
            ["submissions.submission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accepted_submission_id"),
    )
    with op.batch_alter_table("solves", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_solves_slug"), ["slug"], unique=False)

    op.create_table(
        "review_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("solve_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["problems.slug"],
        ),
        sa.ForeignKeyConstraint(
            ["solve_id"],
            ["solves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_log_slug"), ["slug"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_log_slug"))

    op.drop_table("review_log")
    with op.batch_alter_table("solves", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_solves_slug"))

    op.drop_table("solves")
    op.drop_table("solution_analysis")
    op.drop_table("suggestions")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_timestamp"))
        batch_op.drop_index(batch_op.f("ix_submissions_slug"))
        batch_op.drop_index(batch_op.f("ix_submissions_code_hash"))

    op.drop_table("submissions")
    op.drop_table("skill_edges")
    with op.batch_alter_table("problem_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_problem_skills_skill_id"))

    op.drop_table("problem_skills")
    op.drop_table("problem_analysis")
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_due"))

    op.drop_table("cards")
    op.drop_table("sync_state")
    op.drop_table("skills")
    op.drop_table("settings")
    op.drop_table("problems")
    op.drop_table("insights")
    # ### end Alembic commands ###
