"""problem sync fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 22:49:34.005244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.add_column(sa.Column("frontend_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("is_paid_only", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("question_status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_result", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_submitted_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("num_submitted", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.drop_column("num_submitted")
        batch_op.drop_column("last_submitted_at")
        batch_op.drop_column("last_result")
        batch_op.drop_column("question_status")
        batch_op.drop_column("is_paid_only")
        batch_op.drop_column("frontend_id")

    # ### end Alembic commands ###
